// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_rcroft1.Models;

namespace Mission06_rcroft1.Migrations
{
    [DbContext(typeof(MovieSuggestionContext))]
    partial class MovieSuggestionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_rcroft1.Models.MovieData", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            director = "Joel Crawford",
                            edited = false,
                            rating = "Pg",
                            title = "Puss in Boots",
                            year = 2023
                        },
                        new
                        {
                            MovieId = 2,
                            director = "Andrew Adamson",
                            edited = false,
                            notes = "Best movie ever",
                            rating = "Pg",
                            title = "Shreck",
                            year = 2001
                        },
                        new
                        {
                            MovieId = 3,
                            director = "Conrad Vernon",
                            edited = false,
                            notes = "Second best movie ever",
                            rating = "Pg",
                            title = "Shreck 2",
                            year = 2004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
